### PR TITLE
Simplifies typings on `just-compare`

### PR DESCRIPTION
**Pull request by neil-morrison44**
Fixes https://github.com/angus-c/just/issues/476

- Typings now just take 2 values of unknown type & returns a boolean, which matches the JS

### CODE REVIEW

**Comment by angus-c** [comment]
Thank you!

**Comment by angus-c** [comment]
@neil-morrison44 FYI The TS tests now fail because it (correctly) no longer expects an error. So just need to remove the @ts-expect-error comments [here](https://github.com/angus-c/just/blob/master/packages/collection-compare/index.tests.ts#L55-L76)

**Comment by angus-c** [comment]
Published as just-compare@2.2.1 (I intended to make this a minor bump but I messed up 😄 )

**Comment by sven-nyffenegger** [comment]
@neil-morrison44 @angus-c I'm wondering what the motivation was to remove the typings? This change removes the ability to make use of generics (which was fixed with #460)

**Comment by neil-morrison44** [comment]
@sven-nyffenegger the linked issue explains it fairly well I think - it's mostly to be a better representation of the underlying JS rather than presuming the two things being compared are the same type.

If you were writing a pure TS function with the same functionality as the JS (i.e. you can compare across types) I think you'd be required to use `unknown`. 

Supplying _extra_ opinions / constraints on top of that (like that the two inputs should be of the same type) shouldn't be the place of the .d.TS typings.

**Pull request merged**
