### PR TITLE
rename esm modules to `.mjs`

### PR DESCRIPTION
**Pull request by angus-c**

### CODE REVIEW

**Comment by angus-c** [comment]
@PuruVJ @raulfdm @brandonryan @JakeChampion @rqbazan @nosovk 

OK I've renamed all ESM modules to have `.mjs` suffix. This should make esm modules recognizable to NodeJS, sveltekit, next and others consumers.

Unless there are objections I'm going to merge this.

Remaining optimizations that I can see we might want: 
- Add ./package.json to exports #343 
- Switch to manually writing esm modules and using rollup to auto-generate CJS (as per @PuruVJ ESM -> CJS generation is more reliable than vice versa)

Feedback welcome!

**Comment by raulfdm** [comment]
Hey @angus-c .

I've created a repository that can help you to test within different apps: https://github.com/devraul/just-test

I tried to write a minimum README so you can understand how to do.

Take a look and let me know if there's anything else I can help you with.

**Comment by angus-c** [comment]
Thanks @raulfdm, will take a look tomorrow.

**Comment by angus-c** [comment]
Hey @raulfdm, love `just-test`! I'm going to link it from `CONTRIBUTING.md`. 
BTW I didn't need verdaccio, I just used `yarn pack` to build a tarball and then `yarn add <tarball.tgz>` in `just-test`.

All apps passed with this PR (`rename esm modules to .mjs`) except both sveltekit tests failed.
```
pnpm run test-just --filter sveltekit-static

> sveltekit-static@0.0.1 test-just /Users/anguscroll/Documents/github/just-test/apps/sveltekit-static
> svelte-kit build

file:///Users/anguscroll/Documents/github/just-test/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.195_svelte@3.44.1/node_modules/@sveltejs/kit/dist/cli.js:856
                        https = https || !!vite_config.server?.https;
                                                              ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
/Users/anguscroll/Documents/github/just-test/apps/sveltekit-static:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  sveltekit-static@0.0.1 test-just: `svelte-kit build`
Exit status 1
```
Not sure what the issue is here.

**Comment by PuruVJ** [comment]
just-diff is still exporting an object as default, so it won't work 🥲

**Comment by angus-c** [comment]
> just-diff is still exporting an object as default, so it won't work 🥲

https://github.com/angus-c/just/blob/master/packages/collection-diff/index.mjs#L146

**Comment by PuruVJ** [comment]
Ohhh my bad 😅

**Comment by PuruVJ** [comment]
Maybe it;s how we're exporting in package.json that's an isssue. Maybe have a look at how I am doing it in all-of-just? https://github.com/PuruVJ/all-of-just/blob/main/package.json

PS: this package.json ends up in dist, so that's why paths are relative to dist only

**Comment by angus-c** [comment]
@PuruVJ just to be clear, I'm not sure there is a problem with this PR. It passes in every app type in @raulfdm's just-test except sveletekit. Need someone to test it in RL sveltekit instance to confirm whether this is an issue. Regardless landing this PR made a big improvement across the app ecosystem and I don't want to rush to make patches for one app type if they will break other apps or compromise established standards.

The only difference I see with all-of-just is your `export` statement includes `module` and `import` properties while this PR uses `default`. According to [node spec](https://nodejs.org/api/packages.html) `default` is the fallback for all non-mentioned properties so this should work the same or better.

**Comment by raulfdm** [comment]
@angus-c about testing in a real Sveltekit, https://github.com/angus-c/just/issues/332#issuecomment-955766100 check this comment.  This "MailCheck" website uses Sveltekit and a particular "just-*" package. 

What you can do to see in is cloning this repository inside `just-test/apps/`, checking which just package it uses, try the `.mjs` fix and see if the build happens. If not then we have to take a closer look if there's a problem with Sveltekit + Vite (I know there are some issues there related to modules but I'm not sure if it's the same).

**Comment by angus-c** [comment]
Thanks @raulfdm. Will check when I have a chance (also this PR is now published so I will ask the app author directly)

**Comment by nosovk** [comment]
@angus-c @raulfdm 
https://github.com/MailCheck-co/mailcheck.site/commit/f0581d6f2485851f5eb898cfc77582eec7474be4
I've updated to latest version and it seems that all works in proper way in SvelteKit for now.

**Comment by angus-c** [comment]
@nosovk great, thanks for letting me know

**Pull request merged**
