### PR TITLE
fix module type detection

### PR DESCRIPTION
**Pull request by nosovk**
https://github.com/angus-c/just/issues/332
removing that line will allow autodetect to work correctly.
todo: more build targets available, see: https://github.com/pngwn/MDsveX/blob/master/packages/mdsvex/rollup.config.js

### CODE REVIEW

**Comment by angus-c** [comment]
@raulfdm what do you think?

**Comment by nosovk** [comment]
looks like that PR also needed 🤷

**Comment by angus-c** [comment]
Ok I merged, thank you.
However I'm AFK right now and can't verify that commonjs usage still works as before with this change. I will publish once I have run this check

**Comment by rqbazan** [comment]
Hey @angus-c 

I've just tested `just-map-values` using [patch-package](https://github.com/ds300/patch-package). It works 🔥

- Reproduce: https://github.com/rqbazan/just-commonjs-test
- Patch: https://github.com/rqbazan/just-commonjs-test/blob/b4726c23ed78dc65278d8a229fbf4aedcaaf053d/patches/just-map-values%2B2.2.0.patch

**Comment by angus-c** [comment]
Ok all versioned and published. Let me know if you have any more issues @nosovk @rqbazan

**Comment by nosovk** [comment]
Unfortunately it didn't help
image
https://github.com/MailCheck-co/mailcheck.site/pull/608 PR to update svelte kit to the latest version. Will check it a bit later, currently it fails with the same error :(

**Pull request merged**
