### PR TITLE
Types: better generic type for just-union

### PR DESCRIPTION
**Pull request by kathawala**
Adds better support for readonly arrays to the types for `just-union`.

See example:

just-array-const

### CODE REVIEW

**Comment by brandonryan** [comment]
If you could update the test to include that type check that would be great.

**Comment by kathawala** [comment]
@brandonryan which type check do I need to include? Do I need to rebase on master or is it something else?

**Comment by brandonryan** [comment]
add
```ts
const test4: [1, 2, 3, "a", "b", "c"] = union([1, 2, 3], ["a", "b", "c"]);
```
in `packages/array-union/index.tests.ts`

Im not a maintainer, that just my suggestion.

**Comment by angus-c** [comment]
Thanks! I will add the ts test @brandonryan suggested

**Pull request merged**
