### PR TITLE
just-sort-by

### PR DESCRIPTION
**Pull request by EvandroLG**
A simple implementation of `sortBy`.
I'm still wondering if we could add more features to this function. WDYT @angus-c ?

### CODE REVIEW

**Comment by TonalidadeHidrica** [comment]
I'm completely a newcomer who realized this awesome repository ten minutes ago, but I have an idea:  how about accepting a key-extracting function for the second argument, not only property name?  @EvandroLG

**Comment by EvandroLG** [comment]
@TonalidadeHidrica I liked your idea! I'm going to implement it (maybe this weekend) :)
Tks @TonalidadeHidrica

**Comment by angus-c** [comment]
I'll wait for your update before reviewing, @EvandroLG 
Sorry going a bit slow with PRs at the moment due to other tasks. But this looks like a useful util!

**Comment by TonalidadeHidrica** [comment]
@EvandroLG In my humble opinion, case-insensitive sort by default may be quite unintuitive and might be a trap.  Also, maybe you should use a comparison operator instead of subtracting for non-string type?

**Comment by angus-c** [comment]
I like this but I would prefer if you remove support for iterator function. Reason: it just adds more code and there is no reason someone would use it over native `sort`

**Comment by EvandroLG** [comment]
I disagree @angus-c. The iterator function is much simpler than the native sort from JavaScript, you just need to select what you want to compare. Also, for adding the support for iterator function, I just added two more lines.

**Comment by angus-c** [comment]
Yeah I read the code wrong, sorry. I think then it might be better to show a more complex use case for the function argument, to show why it might be necessary instead of a string argument.

e.g.
```
sortBy([
  {user: 'fabio', details: {city: "Milan", age: 34}},
  {user: 'max', details: {city: "Munich", age: 29}},
  {user: 'zacarias', details: {city: "São Paulo", age: 44}},
  {user: 'robert', details: {city: "Manchester", age: 28}},
  {user: 'klaus', details: {city: "Zurich", age: 38}},
], function(o) {
  return o.details.age;
});
```

**Comment by angus-c** [comment]
thanks!

**Pull request merged**
